# Hugo D3.js Stacked Bar Chart Demo Configuration
# Modern Hugo configuration with D3.js data visualization features

baseURL = "http://localhost:1313/"
title = "Hugo D3.js Stacked Bar Chart Demo"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
enableMissingTranslationPlaceholders = true

# Security settings
[security]
  enableInlineShortcodes = true
  [security.exec]
    allow = ["^git$"]

# Build settings
[build]
  writeStats = true
  useResourceCacheWhen = "fallback"

# Language configurations
[languages]
  [languages.ja]
    languageName = "日本語"
    languageCode = "ja"
    weight = 1
    [languages.ja.params]
      site_description = "D3.jsスタック棒グラフデモの多言語対応Hugoサイト"
      site_author = "Your Name <your.email@example.com>"
      site_keywords = "hugo, d3js, データ可視化, スタック棒グラフ, 多言語, テンプレート, 日本語"
      theme_color = "#2c3e50"
      background_color = "#ffffff"
      
  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 2
    [languages.en.params]
      site_description = "Multilingual Hugo site demonstrating D3.js stacked bar chart visualization"
      site_author = "Your Name <your.email@example.com>"
      site_keywords = "hugo, d3js, data visualization, stacked bar chart, multilingual, template, english"
      theme_color = "#2c3e50"
      background_color = "#ffffff"

# Menu configurations
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

